apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: storage
  labels:
    {{- include "karpenter-nvme.labels" . | nindent 4 }}
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: nvme
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            {{- toYaml .Values.nodePool.capacityTypes | nindent 12 }}
        - key: karpenter.k8s.aws/instance-local-nvme
          operator: Gt
          values: [{{ .Values.nodePool.minNvmeGiB | quote }}]
        - key: kubernetes.io/arch
          operator: In
          values:
            {{- toYaml .Values.nodePool.architectures | nindent 12 }}
  limits:
    cpu: {{ .Values.nodePool.limits.cpu | quote }}
    memory: {{ .Values.nodePool.limits.memory | quote }}
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: {{ .Values.nodePool.consolidateAfter }}
    budgets:
      - nodes: {{ .Values.nodePool.disruptionBudget.nodes | quote }}
  weight: {{ .Values.nodePool.weight }}
